services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
        - /var/lib/jellyfin:/config
        - /var/cache/jellyfin:/cache
        - /srv/media:/media
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - /var/lib/qbittorrent:/config
      - /srv/media/downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - 8989:8989
    volumes:
      - /var/lib/sonarr/data:/config
      - /srv/media/shows:/tv
      - /srv/media/downloads:/downloads
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - 7878:7878
    volumes:
      - /var/lib/radarr/data:/config
      - /srv/media/movies:/movies
      - /srv/media/downloads:/downloads
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - 9696:9696
    volumes:
      - /home/mihir/home-server/prowlarr-config:/config
    restart: unless-stopped
