services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
        - /var/lib/jellyfin:/config
        - /var/cache/jellyfin:/cache
        - /srv/media:/media
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - /var/lib/qbittorrent:/config
      - /srv/media:/media
    restart: unless-stopped
